description = "Initializ Buildpack for Go and Nodejs"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/go:1.22.1"
  version = "1.22.1"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/nodejs:2.2.6"
  version = "2.2.6"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/procfile:5.6.20"
  version = "5.6.20"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/web-servers:1.0.10"
  version = "1.0.10"

[lifecycle]
  version = "0.19.7"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/go"
    version = "1.22.1"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/web-servers"
    version = "1.0.10"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/nodejs"
    version = "2.2.6"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    version = "5.6.20"

[stack]
  build-image = "docker.io/initializbuildpacks/go-securepack-build:9.9.9"
  id = "Initializ Distroless Stack"
  run-image = "docker.io/initializbuildpacks/securepacks-run:latest"
  run-image-mirrors = []
