description = "Initializ Buildpack for Go and Nodejs application"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/go:2.0.0"
  version = "2.0.0"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/nodejs:3.0.2"
  version = "3.0.2"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/procfile:5.6.21"
  version = "5.6.21"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/web-servers:1.0.15"
  version = "1.0.15"

[lifecycle]
  version = "0.20.3"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/go"
    version = "2.0.0"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/web-servers"
    version = "1.0.15"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/nodejs"
    version = "3.0.2"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    version = "5.6.21"

[stack]
  build-image = "docker.io/initializbuildpacks/go-securepack-build:9.9.9"
  id = "Initializ Distroless Stack"
  run-image = "docker.io/initializbuildpacks/securepacks-run:latest"
  run-image-mirrors = []
